// Side drawer showing the generated Bicep. Read-mostly (CLAUDE.md
// §11 — not a Bicep IDE). Has copy + save-as-template actions.

import { useState } from "react";
import { createTemplate } from "../../lib/api";

type Props = {
  open: boolean;
  bicep: string | null;
  onClose: () => void;
  onSaved: (templateName: string) => void;
};

export function BicepDrawer({ open, bicep, onClose, onSaved }: Props) {
  const [savingName, setSavingName] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);

  if (!open) return null;

  const copy = async () => {
    if (!bicep) return;
    try {
      await navigator.clipboard.writeText(bicep);
      setCopied(true);
      setTimeout(() => setCopied(false), 1500);
    } catch {
      // best-effort
    }
  };

  const save = async () => {
    if (!bicep || !savingName) return;
    setError(null);
    setBusy(true);
    try {
      const t = await createTemplate({ name: savingName, bicep });
      onSaved(t.name);
      setSavingName(null);
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
    } finally {
      setBusy(false);
    }
  };

  return (
    <div
      className="fixed inset-0 z-50 bg-on-surface/40 backdrop-blur-sm flex justify-end"
      onClick={onClose}
    >
      <div
        className="w-full max-w-2xl h-full bg-surface-container-lowest shadow-2xl flex flex-col"
        onClick={(e) => e.stopPropagation()}
      >
        <div className="px-6 py-4 border-b border-outline-variant/30 flex items-center justify-between gap-2">
          <div>
            <h2 className="text-base font-extrabold tracking-tight">Bicep</h2>
            <p className="text-xs text-on-surface-variant">
              Generated by Claude. Review before pushing.
            </p>
          </div>
          <div className="flex items-center gap-2">
            <button
              type="button"
              onClick={copy}
              className="px-3 py-1.5 rounded-lg border border-outline-variant/40 text-xs font-semibold hover:bg-surface-container-high transition-colors"
            >
              {copied ? "Copied" : "Copy"}
            </button>
            <button
              type="button"
              onClick={onClose}
              className="text-on-surface-variant hover:text-on-surface p-1 rounded-md hover:bg-surface-container-high"
              aria-label="Close"
            >
              <span className="material-symbols-outlined">close</span>
            </button>
          </div>
        </div>

        <div className="flex-1 overflow-auto bg-surface-container-low">
          {bicep ? (
            <pre className="font-mono text-[12px] leading-relaxed p-6 whitespace-pre-wrap break-words">
              {bicep}
            </pre>
          ) : (
            <div className="grid place-items-center h-full text-sm text-on-surface-variant">
              No Bicep yet. Ask Claude to design something.
            </div>
          )}
        </div>

        {bicep && (
          <div className="border-t border-outline-variant/30 p-4 space-y-2">
            {savingName === null ? (
              <button
                type="button"
                onClick={() => setSavingName("")}
                className="w-full px-3 py-2 rounded-lg border border-outline-variant/40 text-sm font-semibold hover:bg-surface-container-high transition-colors flex items-center justify-center gap-2"
              >
                <span className="material-symbols-outlined text-base">
                  bookmark_add
                </span>
                Save as template
              </button>
            ) : (
              <div className="flex items-end gap-2">
                <label className="flex-1 block">
                  <span className="text-[10px] font-extrabold uppercase tracking-widest text-on-surface-variant">
                    Template name
                  </span>
                  <input
                    type="text"
                    autoFocus
                    value={savingName}
                    onChange={(e) => setSavingName(e.target.value)}
                    onKeyDown={(e) => {
                      if (e.key === "Enter") void save();
                      if (e.key === "Escape") setSavingName(null);
                    }}
                    placeholder="vigil-baseline"
                    className="mt-1 w-full p-2 rounded-lg bg-surface-container-low border border-outline-variant/40 text-sm focus:outline-none focus:ring-2 focus:ring-primary/30"
                  />
                </label>
                <button
                  type="button"
                  onClick={() => setSavingName(null)}
                  disabled={busy}
                  className="px-3 py-2 rounded-lg border border-outline-variant/40 text-sm font-semibold hover:bg-surface-container-high disabled:opacity-50"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={save}
                  disabled={busy || !savingName.trim()}
                  className="px-3 py-2 rounded-lg bg-gradient-to-br from-primary to-primary-container text-on-primary text-sm font-semibold shadow-sm disabled:opacity-50 hover:brightness-110"
                >
                  {busy ? "Saving…" : "Save"}
                </button>
              </div>
            )}
            {error && (
              <div className="rounded-lg bg-error/5 border border-error/30 p-2 text-xs text-error">
                {error}
              </div>
            )}
          </div>
        )}
      </div>
    </div>
  );
}
